brand:
  name: Codehero
  facebook: codeheroblog
  twitter: codeheroblog
  gplus: '114001556421077350451'
  github: codeheroco

  disqus:
    shortname: codeheroblog

  analytics:
    google: 'UA-41464412-1'

timezone: America/Caracas
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'config.rb', 'Rakefile']
future: false

permalink: none
paginate_path: 'page:num'
paginate: 10

markdown: redcarpet
pygments: true

host: 0.0.0.0
port: 3000
baseurl: /

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascript
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
